default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: search_development
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] %>
  port: <%= ENV["DB_PORT"] || 5432 %>

test:
  <<: *default
  database: search_test
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] %>
  port: <%= ENV["DB_PORT"] || 5432 %>

production: &primary_production
  <<: *default
  database: <%= ENV["DB_NAME"] %>
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] %>
  port: <%= ENV["DB_PORT"] || 5432 %>
  url: <%= ENV["DB_URL"] %>

  cache:
    <<: *primary_production
    database: search_production_cache
    migrations_paths: db/cache_migrate

  queue:
    <<: *primary_production
    database: search_production_queue
    migrations_paths: db/queue_migrate

  cable:
    <<: *primary_production
    database: <%= ENV["DB_NAME"] %>
    migrations_paths: db/cable_migrate